/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projectrost;

import java.awt.Color;
import java.awt.Point;
import java.util.Set;
import javax.swing.BorderFactory;
import javax.swing.JFrame;

/**
 *
 * @author Geetha
 */
public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public NewJFrame1() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(4, 4, 4, 4, Color.black));
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigationPanel = new javax.swing.JPanel();
        MyBackUpsButton = new javax.swing.JButton();
        navBackUpButton = new javax.swing.JButton();
        navRestoreButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();
        homePanel = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        connectPanel = new javax.swing.JPanel();
        connectButton = new javax.swing.JButton();
        loadingPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        backUpAndRestorePanel = new javax.swing.JPanel();
        backUpButton = new javax.swing.JButton();
        restoreButton = new javax.swing.JButton();
        backUpPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        audioButton = new javax.swing.JButton();
        contactsButton = new javax.swing.JButton();
        smsButton = new javax.swing.JButton();
        documentsButton = new javax.swing.JButton();
        videoButton = new javax.swing.JButton();
        picturesButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        finalBackUpButton = new javax.swing.JButton();
        backUpLoadingPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        restorePanel = new javax.swing.JPanel();
        finalRestoreButton = new javax.swing.JButton();
        restoreLoadingPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        myBackUpsPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        helpPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        aboutPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        logoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        closeLabel = new javax.swing.JLabel();
        minimizeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);

        navigationPanel.setBackground(new java.awt.Color(102, 0, 102));

        MyBackUpsButton.setBackground(new java.awt.Color(255, 255, 255));
        MyBackUpsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MyBackUpsButton.setText("My BackUps");
        MyBackUpsButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        MyBackUpsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyBackUpsButtonActionPerformed(evt);
            }
        });

        navBackUpButton.setBackground(new java.awt.Color(255, 255, 255));
        navBackUpButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        navBackUpButton.setText("BackUp");
        navBackUpButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        navBackUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navBackUpButtonActionPerformed(evt);
            }
        });

        navRestoreButton.setBackground(new java.awt.Color(255, 255, 255));
        navRestoreButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        navRestoreButton.setText("Restore");
        navRestoreButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        navRestoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navRestoreButtonActionPerformed(evt);
            }
        });

        helpButton.setBackground(new java.awt.Color(255, 255, 255));
        helpButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        helpButton.setText("Help");
        helpButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        aboutButton.setBackground(new java.awt.Color(255, 255, 255));
        aboutButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aboutButton.setText("About");
        aboutButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
        navigationPanel.setLayout(navigationPanelLayout);
        navigationPanelLayout.setHorizontalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MyBackUpsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navBackUpButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(navRestoreButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(helpButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(aboutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        navigationPanelLayout.setVerticalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addComponent(MyBackUpsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navBackUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navRestoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aboutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        homePanel.setBackground(new java.awt.Color(255, 255, 255));
        homePanel.setName(""); // NOI18N
        homePanel.setLayout(new java.awt.CardLayout());

        startButton.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        startButton.setText("WelcomePanel");
        startButton.setOpaque(false);
        startButton.setContentAreaFilled(false);
        startButton.setBorderPainted(false);
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        homePanel.add(startButton, "card2");

        connectPanel.setBackground(new java.awt.Color(255, 255, 255));

        connectButton.setBackground(new java.awt.Color(255, 255, 255));
        connectButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        connectButton.setText("CONNECT");
        connectButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                connectButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                connectButtonMouseExited(evt);
            }
        });
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout connectPanelLayout = new javax.swing.GroupLayout(connectPanel);
        connectPanel.setLayout(connectPanelLayout);
        connectPanelLayout.setHorizontalGroup(
            connectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectPanelLayout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(connectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(257, Short.MAX_VALUE))
        );
        connectPanelLayout.setVerticalGroup(
            connectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, connectPanelLayout.createSequentialGroup()
                .addContainerGap(424, Short.MAX_VALUE)
                .addComponent(connectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        homePanel.add(connectPanel, "card9");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Panel Reserved For Loading Screen...");

        javax.swing.GroupLayout loadingPanelLayout = new javax.swing.GroupLayout(loadingPanel);
        loadingPanel.setLayout(loadingPanelLayout);
        loadingPanelLayout.setHorizontalGroup(
            loadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadingPanelLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        loadingPanelLayout.setVerticalGroup(
            loadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadingPanelLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        homePanel.add(loadingPanel, "card10");

        backUpAndRestorePanel.setBackground(new java.awt.Color(255, 255, 255));

        backUpButton.setBackground(new java.awt.Color(255, 255, 255));
        backUpButton.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        backUpButton.setForeground(new java.awt.Color(255, 255, 255));
        backUpButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Geetha\\Desktop\\backup.png")); // NOI18N
        backUpButton.setBorder(null);
        backUpButton.setContentAreaFilled(false);
        backUpButton.setBorderPainted(false);
        backUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backUpButtonActionPerformed(evt);
            }
        });

        restoreButton.setBackground(new java.awt.Color(255, 255, 255));
        restoreButton.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        restoreButton.setForeground(new java.awt.Color(255, 255, 255));
        restoreButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Geetha\\Desktop\\restore.png")); // NOI18N
        restoreButton.setBorder(null);
        restoreButton.setContentAreaFilled(false);
        restoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoreButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backUpAndRestorePanelLayout = new javax.swing.GroupLayout(backUpAndRestorePanel);
        backUpAndRestorePanel.setLayout(backUpAndRestorePanelLayout);
        backUpAndRestorePanelLayout.setHorizontalGroup(
            backUpAndRestorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backUpAndRestorePanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(backUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(restoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        backUpAndRestorePanelLayout.setVerticalGroup(
            backUpAndRestorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backUpAndRestorePanelLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(backUpAndRestorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        homePanel.add(backUpAndRestorePanel, "card3");

        backUpPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("BackUp Destination");

        audioButton.setBackground(new java.awt.Color(255, 255, 255));
        audioButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        audioButton.setText("AUDIO");
        audioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioButtonActionPerformed(evt);
            }
        });

        contactsButton.setBackground(new java.awt.Color(255, 255, 255));
        contactsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contactsButton.setText("CONTACTS");
        contactsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactsButtonActionPerformed(evt);
            }
        });

        smsButton.setBackground(new java.awt.Color(255, 255, 255));
        smsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        smsButton.setText("SMS");
        smsButton.setBorder(null);
        smsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                smsButtonMouseClicked(evt);
            }
        });
        smsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smsButtonActionPerformed(evt);
            }
        });

        documentsButton.setBackground(new java.awt.Color(255, 255, 255));
        documentsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        documentsButton.setText("DOCUMENTS");
        documentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentsButtonActionPerformed(evt);
            }
        });

        videoButton.setBackground(new java.awt.Color(255, 255, 255));
        videoButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        videoButton.setText("VIDEO");
        videoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoButtonActionPerformed(evt);
            }
        });

        picturesButton.setBackground(new java.awt.Color(255, 255, 255));
        picturesButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        picturesButton.setText("PICTURES");
        picturesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                picturesButtonActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("BackUp Name");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Select the categories to backup");

        finalBackUpButton.setBackground(new java.awt.Color(255, 255, 255));
        finalBackUpButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        finalBackUpButton.setText("BACKUP");
        finalBackUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                finalBackUpButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                finalBackUpButtonMouseExited(evt);
            }
        });
        finalBackUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalBackUpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backUpPanelLayout = new javax.swing.GroupLayout(backUpPanel);
        backUpPanel.setLayout(backUpPanelLayout);
        backUpPanelLayout.setHorizontalGroup(
            backUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backUpPanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(backUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(smsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(audioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(documentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(backUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contactsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(picturesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(videoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
            .addGroup(backUpPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(backUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(finalBackUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(backUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(backUpPanelLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(377, Short.MAX_VALUE)))
        );
        backUpPanelLayout.setVerticalGroup(
            backUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backUpPanelLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(backUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(smsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(audioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(videoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(documentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(picturesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(backUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backUpPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(70, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backUpPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(finalBackUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(backUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(backUpPanelLayout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(429, Short.MAX_VALUE)))
        );

        homePanel.add(backUpPanel, "card4");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setText("Panel Reserved For BackUp Loading Screen...");

        javax.swing.GroupLayout backUpLoadingPanelLayout = new javax.swing.GroupLayout(backUpLoadingPanel);
        backUpLoadingPanel.setLayout(backUpLoadingPanelLayout);
        backUpLoadingPanelLayout.setHorizontalGroup(
            backUpLoadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backUpLoadingPanelLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        backUpLoadingPanelLayout.setVerticalGroup(
            backUpLoadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backUpLoadingPanelLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        homePanel.add(backUpLoadingPanel, "card11");

        restorePanel.setBackground(new java.awt.Color(255, 255, 255));

        finalRestoreButton.setBackground(new java.awt.Color(255, 255, 255));
        finalRestoreButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        finalRestoreButton.setText("RESTORE");
        finalRestoreButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                finalRestoreButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                finalRestoreButtonMouseExited(evt);
            }
        });
        finalRestoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalRestoreButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout restorePanelLayout = new javax.swing.GroupLayout(restorePanel);
        restorePanel.setLayout(restorePanelLayout);
        restorePanelLayout.setHorizontalGroup(
            restorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, restorePanelLayout.createSequentialGroup()
                .addContainerGap(526, Short.MAX_VALUE)
                .addComponent(finalRestoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        restorePanelLayout.setVerticalGroup(
            restorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, restorePanelLayout.createSequentialGroup()
                .addContainerGap(435, Short.MAX_VALUE)
                .addComponent(finalRestoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        homePanel.add(restorePanel, "card5");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel12.setText("Panel Reserved For Restore Loading Screen...");

        javax.swing.GroupLayout restoreLoadingPanelLayout = new javax.swing.GroupLayout(restoreLoadingPanel);
        restoreLoadingPanel.setLayout(restoreLoadingPanelLayout);
        restoreLoadingPanelLayout.setHorizontalGroup(
            restoreLoadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restoreLoadingPanelLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        restoreLoadingPanelLayout.setVerticalGroup(
            restoreLoadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(restoreLoadingPanelLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        homePanel.add(restoreLoadingPanel, "card12");

        myBackUpsPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setText("MyBackUp");

        javax.swing.GroupLayout myBackUpsPanelLayout = new javax.swing.GroupLayout(myBackUpsPanel);
        myBackUpsPanel.setLayout(myBackUpsPanelLayout);
        myBackUpsPanelLayout.setHorizontalGroup(
            myBackUpsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
            .addGroup(myBackUpsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(myBackUpsPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        myBackUpsPanelLayout.setVerticalGroup(
            myBackUpsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
            .addGroup(myBackUpsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(myBackUpsPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        homePanel.add(myBackUpsPanel, "card8");

        helpPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("Help Panel");

        javax.swing.GroupLayout helpPanelLayout = new javax.swing.GroupLayout(helpPanel);
        helpPanel.setLayout(helpPanelLayout);
        helpPanelLayout.setHorizontalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpPanelLayout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        helpPanelLayout.setVerticalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpPanelLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        homePanel.add(helpPanel, "card6");

        aboutPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("About Panel");

        javax.swing.GroupLayout aboutPanelLayout = new javax.swing.GroupLayout(aboutPanel);
        aboutPanel.setLayout(aboutPanelLayout);
        aboutPanelLayout.setHorizontalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
            .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aboutPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        aboutPanelLayout.setVerticalGroup(
            aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
            .addGroup(aboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(aboutPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        homePanel.add(aboutPanel, "card7");

        logoPanel.setBackground(new java.awt.Color(0, 0, 0));
        logoPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoPanelMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Geetha\\Desktop\\imgonline-com-ua-resize-YRkRdHl8J2H1.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoPanelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        topPanel.setBackground(new java.awt.Color(102, 0, 102));
        topPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topPanelMouseDragged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ROST Backup & Restore");

        closeLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        closeLabel.setForeground(new java.awt.Color(255, 255, 255));
        closeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLabel.setText("X");
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });

        minimizeLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        minimizeLabel.setForeground(new java.awt.Color(255, 255, 255));
        minimizeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizeLabel.setText("-");
        minimizeLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        minimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(minimizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(closeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(closeLabel)
                        .addComponent(minimizeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(navigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(navigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navBackUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navBackUpButtonActionPerformed
        // TODO add your handling code here:
        homePanel.removeAll();
        homePanel.add(backUpPanel);
        homePanel.repaint();
        homePanel.revalidate();
    }//GEN-LAST:event_navBackUpButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        homePanel.removeAll();
        homePanel.add(connectPanel);
        homePanel.repaint();
        homePanel.revalidate();
    }//GEN-LAST:event_startButtonActionPerformed

    private void backUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backUpButtonActionPerformed
        // TODO add your handling code here:
        homePanel.removeAll();
        homePanel.add(backUpPanel);
        homePanel.repaint();
        homePanel.revalidate();
    }//GEN-LAST:event_backUpButtonActionPerformed

    private void restoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoreButtonActionPerformed
        homePanel.removeAll();
        homePanel.add(restorePanel);
        homePanel.repaint();
        homePanel.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_restoreButtonActionPerformed

    private void navRestoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navRestoreButtonActionPerformed
        // TODO add your handling code here:
        homePanel.removeAll();
        homePanel.add(restorePanel);
        homePanel.repaint();
        homePanel.revalidate();
    }//GEN-LAST:event_navRestoreButtonActionPerformed

    private void MyBackUpsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyBackUpsButtonActionPerformed
        // TODO add your handling code here:
         homePanel.removeAll();
        homePanel.add(myBackUpsPanel);
        homePanel.repaint();
        homePanel.revalidate();
    }//GEN-LAST:event_MyBackUpsButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        // TODO add your handling code here:
         homePanel.removeAll();
        homePanel.add(helpPanel);
        homePanel.repaint();
        homePanel.revalidate();
    }//GEN-LAST:event_helpButtonActionPerformed

    private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButtonActionPerformed
        // TODO add your handling code here:
         homePanel.removeAll();
        homePanel.add(aboutPanel);
        homePanel.repaint();
        homePanel.revalidate();
    }//GEN-LAST:event_aboutButtonActionPerformed

    private void logoPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoPanelMouseClicked
        // TODO add your handling code here:
         homePanel.removeAll();
        homePanel.add(backUpAndRestorePanel);
        homePanel.repaint();
        homePanel.revalidate();
    }//GEN-LAST:event_logoPanelMouseClicked

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeLabelMouseClicked

    private void minimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeLabelMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeLabelMouseClicked

    private void topPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topPanelMouseDragged
        // TODO add your handling code here:
        Point p=evt.getLocationOnScreen();
        this.setLocation(p);
    }//GEN-LAST:event_topPanelMouseDragged

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        // TODO add your handling code here:
        homePanel.removeAll();
        homePanel.add(loadingPanel);
        homePanel.repaint();
        homePanel.revalidate();
    }//GEN-LAST:event_connectButtonActionPerformed
    int is=0;
    private void smsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smsButtonActionPerformed
        // TODO add your handling code here:
        is++;
            if(is%2!=0){
                smsButton.setBackground(new Color(102,0,102));
                smsButton.setForeground(new Color(255,255,255));
            }
            else{
                smsButton.setBackground(new Color(255,255,255));
                smsButton.setForeground(new Color(0,0,0));
            }
        
    }//GEN-LAST:event_smsButtonActionPerformed
    int ic=0;
    private void contactsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactsButtonActionPerformed
        // TODO add your handling code here:
        ic++;
            if(ic%2!=0){
                contactsButton.setBackground(new Color(102,0,102));
                contactsButton.setForeground(new Color(255,255,255));
            }
            else{
                contactsButton.setBackground(new Color(255,255,255));
                contactsButton.setForeground(new Color(0,0,0));
            }
    }//GEN-LAST:event_contactsButtonActionPerformed
    int ia=0;
    private void audioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioButtonActionPerformed
        // TODO add your handling code here:
        ia++;
            if(ia%2!=0){
                audioButton.setBackground(new Color(102,0,102));
                audioButton.setForeground(new Color(255,255,255));
            }
            else{
                audioButton.setBackground(new Color(255,255,255));
                audioButton.setForeground(new Color(0,0,0));
            }
     
    }//GEN-LAST:event_audioButtonActionPerformed
    int iv=0;
    private void videoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoButtonActionPerformed
        // TODO add your handling code here:
        iv++;
            if(iv%2!=0){
                videoButton.setBackground(new Color(102,0,102));
                videoButton.setForeground(new Color(255,255,255));
            }
            else{
                videoButton.setBackground(new Color(255,255,255));
                videoButton.setForeground(new Color(0,0,0));
            }
        
    }//GEN-LAST:event_videoButtonActionPerformed
    int id=0;
    private void documentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentsButtonActionPerformed
        // TODO add your handling code here:
        id++;
            if(id%2!=0){
                documentsButton.setBackground(new Color(102,0,102));
                documentsButton.setForeground(new Color(255,255,255));
            }
            else{
                documentsButton.setBackground(new Color(255,255,255));
                documentsButton.setForeground(new Color(0,0,0));
            }
    }//GEN-LAST:event_documentsButtonActionPerformed
    int ip=0;
    private void picturesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_picturesButtonActionPerformed
        // TODO add your handling code here:
        ip++;
            if(ip%2!=0){
                picturesButton.setBackground(new Color(102,0,102));
                picturesButton.setForeground(new Color(255,255,255));
            }
            else{
                picturesButton.setBackground(new Color(255,255,255));
                picturesButton.setForeground(new Color(0,0,0));
            }
    }//GEN-LAST:event_picturesButtonActionPerformed

    private void smsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smsButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_smsButtonMouseClicked

    private void finalBackUpButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finalBackUpButtonMouseEntered
        // TODO add your handling code here:
        finalBackUpButton.setBackground(new Color(102,0,102));
        finalBackUpButton.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_finalBackUpButtonMouseEntered

    private void finalBackUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalBackUpButtonActionPerformed
        // TODO add your handling code here:
        homePanel.removeAll();
        homePanel.add(backUpLoadingPanel);
        homePanel.repaint();
        homePanel.revalidate();
    }//GEN-LAST:event_finalBackUpButtonActionPerformed

    private void finalBackUpButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finalBackUpButtonMouseExited
        // TODO add your handling code here:
        finalBackUpButton.setBackground(new Color(255,255,255));
        finalBackUpButton.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_finalBackUpButtonMouseExited

    private void connectButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectButtonMouseEntered
        // TODO add your handling code here:
        connectButton.setBackground(new Color(102,0,102));
        connectButton.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_connectButtonMouseEntered

    private void connectButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_connectButtonMouseExited
        // TODO add your handling code here:
         connectButton.setBackground(new Color(255,255,255));
        connectButton.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_connectButtonMouseExited

    private void finalRestoreButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finalRestoreButtonMouseEntered
        // TODO add your handling code here:
        finalRestoreButton.setBackground(new Color(102,0,102));
        finalRestoreButton.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_finalRestoreButtonMouseEntered

    private void finalRestoreButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_finalRestoreButtonMouseExited
        // TODO add your handling code here:
         finalRestoreButton.setBackground(new Color(255,255,255));
        finalRestoreButton.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_finalRestoreButtonMouseExited

    private void finalRestoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalRestoreButtonActionPerformed
        // TODO add your handling code here:
        homePanel.removeAll();
        homePanel.add(restoreLoadingPanel);
        homePanel.repaint();
        homePanel.revalidate();
    }//GEN-LAST:event_finalRestoreButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MyBackUpsButton;
    private javax.swing.JButton aboutButton;
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JButton audioButton;
    private javax.swing.JPanel backUpAndRestorePanel;
    private javax.swing.JButton backUpButton;
    private javax.swing.JPanel backUpLoadingPanel;
    private javax.swing.JPanel backUpPanel;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JButton connectButton;
    private javax.swing.JPanel connectPanel;
    private javax.swing.JButton contactsButton;
    private javax.swing.JButton documentsButton;
    private javax.swing.JButton finalBackUpButton;
    private javax.swing.JButton finalRestoreButton;
    private javax.swing.JButton helpButton;
    private javax.swing.JPanel helpPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel loadingPanel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JLabel minimizeLabel;
    private javax.swing.JPanel myBackUpsPanel;
    private javax.swing.JButton navBackUpButton;
    private javax.swing.JButton navRestoreButton;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JButton picturesButton;
    private javax.swing.JButton restoreButton;
    private javax.swing.JPanel restoreLoadingPanel;
    private javax.swing.JPanel restorePanel;
    private javax.swing.JButton smsButton;
    private javax.swing.JButton startButton;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton videoButton;
    // End of variables declaration//GEN-END:variables
}
